vim.cmd([[ set encoding=utf8 ]])
vim.cmd([[ set mouse= ]])
vim.cmd([[ set rnu ]])
vim.cmd([[ set nu ]])
vim.cmd([[ set shiftwidth=2 ]])
vim.cmd([[ set softtabstop=2 ]])
vim.cmd([[ set expandtab ]])
vim.cmd([[ syntax on ]])
vim.cmd([[ highlight Pmenu ctermfg=none  ctermbg=none guibg=none ]])
